### ISSUE TITLE
运行UMI-OCR.exe后， 无任何显示

### ISSUE THREAD

**Issue by phyzjqkl** [hiroi-sora/Umi-OCR_v2#33]
系统win11 i5-1135G7, 但可以看到进程。 系统已装python 3.9. 但系统可以看到进程

![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/36747720/4d836339-b7dd-4082-a7f7-05ee12b5335e)

**Comment by hiroi-sora** [comment]
跟系统python没有关系的。

试下运行 `UmiOCR-data/test_run.bat` 强制启动程序，看看能不能启动

**Comment by phyzjqkl** [comment]
在file explore里双击不行。 在CMD运行就可以了。 谢谢

**Comment by hiroi-sora** [comment]
如果正常从exe双击启动，Umi在系统托盘区的图标能加载出来吗？

**Comment by minakami-akihiro** [comment]
我这边双击exe没有任何反应，在任务栏没有图标也没有进程。但test_run或者用命令行启动exe也可以打开。

**Comment by hiroi-sora** [comment]
在 [之后的版本中](https://github.com/hiroi-sora/Umi-OCR_v2/releases) ，如果 `Umi-OCR.exe` 失效，可以用备用启动器：
```
UmiOCR-data/RUN_GUI.bat
```

它以最大兼容性启动软件，且不显示控制台窗口。

**Comment by GFDGIT** [comment]
你好开发者，

我运行[预览版 dev 20231025](https://github.com/hiroi-sora/Umi-OCR_v2/releases/tag/dev%2F20231025)的`Umi-OCR.exe`、`RUN_GUI.bat`，均没有任何反应。
在CMD中运行`Umi-OCR.exe`，报错如下：

```
D:\Software\Umi-OCR>Umi-OCR.exe

D:\Software\Umi-OCR>Traceback (most recent call last):
  File "D:\Software\Umi-OCR\UmiOCR-data\site-packages\pyzbar\zbar_library.py", line 58, in load
    dependencies, libzbar = load_objects(Path(''))
  File "D:\Software\Umi-OCR\UmiOCR-data\site-packages\pyzbar\zbar_library.py", line 50, in load_objects
    deps = [
  File "D:\Software\Umi-OCR\UmiOCR-data\site-packages\pyzbar\zbar_library.py", line 51, in <listcomp>
    cdll.LoadLibrary(str(directory.joinpath(dep)))
  File "ctypes\__init__.py", line 451, in LoadLibrary
  File "ctypes\__init__.py", line 373, in __init__
FileNotFoundError: Could not find module 'libiconv.dll' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\Umi-OCR\UmiOCR-data\main.py", line 60, in <module>
    runScript()  # 启动脚本
  File "D:\Software\Umi-OCR\UmiOCR-data\main.py", line 55, in runScript
    main()
  File "D:\Software\Umi-OCR\UmiOCR-data\py_src\run.py", line 109, in main
    res = runQml()  # 启动qml
  File "D:\Software\Umi-OCR\UmiOCR-data\py_src\run.py", line 25, in runQml
    from .tag_pages.tag_pages_connector import TagPageConnector  # 页面连接器
  File "C:\Users\RD-01\AppData\Local\Temp\embedded.5c2jaiha.zip\shibokensupport\__feature__.py", line 142, in _import
  File "D:\Software\Umi-OCR\UmiOCR-data\py_src\tag_pages\tag_pages_connector.py", line 15, in <module>
    from .QRcode import QRcode
  File "C:\Users\RD-01\AppData\Local\Temp\embedded.5c2jaiha.zip\shibokensupport\__feature__.py", line 142, in _import
  File "D:\Software\Umi-OCR\UmiOCR-data\py_src\tag_pages\QRcode.py", line 12, in <module>
    import pyzbar.pyzbar as pyzbar
  File "C:\Users\RD-01\AppData\Local\Temp\embedded.5c2jaiha.zip\shibokensupport\__feature__.py", line 142, in _import
  File "D:\Software\Umi-OCR\UmiOCR-data\site-packages\pyzbar\pyzbar.py", line 7, in <module>
    from .wrapper import (
  File "C:\Users\RD-01\AppData\Local\Temp\embedded.5c2jaiha.zip\shibokensupport\__feature__.py", line 142, in _import
  File "D:\Software\Umi-OCR\UmiOCR-data\site-packages\pyzbar\wrapper.py", line 151, in <module>
    zbar_version = zbar_function(
  File "D:\Software\Umi-OCR\UmiOCR-data\site-packages\pyzbar\wrapper.py", line 148, in zbar_function
    return prototype((fname, load_libzbar()))
  File "D:\Software\Umi-OCR\UmiOCR-data\site-packages\pyzbar\wrapper.py", line 127, in load_libzbar
    libzbar, dependencies = zbar_library.load()
  File "D:\Software\Umi-OCR\UmiOCR-data\site-packages\pyzbar\zbar_library.py", line 60, in load
    dependencies, libzbar = load_objects(Path(__file__).parent)
  File "D:\Software\Umi-OCR\UmiOCR-data\site-packages\pyzbar\zbar_library.py", line 54, in load_objects
    libzbar = cdll.LoadLibrary(str(directory.joinpath(fname)))
  File "ctypes\__init__.py", line 451, in LoadLibrary
  File "ctypes\__init__.py", line 373, in __init__
FileNotFoundError: Could not find module 'D:\Software\Umi-OCR\UmiOCR-data\site-packages\pyzbar\libzbar-64.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

此外，[预览版 dev 20231010](https://github.com/hiroi-sora/Umi-OCR_v2/releases/tag/dev%2F20231010)可以正常使用。
麻烦你看一下，谢谢！

**Comment by hiroi-sora** [comment]
@GFDGIT 

感谢提供报错信息。你这个问题与楼上不同，你这是由二维码解码库 pyzbar 不兼容而引起的。所以无论`Umi-OCR.exe`还是`RUN_GUI.bat`都会出现同样的问题。

旧版本（20231018及以前）没有二维码功能，所以不会出现此问题。

关于二维码库兼容性的问题，我会继续调查。

**Comment by hiroi-sora** [comment]
@GFDGIT 

主要的问题出在这里。
```
FileNotFoundError: Could not find module 'libiconv.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

根据网上的一些资料：
https://stackoverflow.com/questions/66792366/could-not-find-module-libiconv-dll-when-trying-to-import-pyzbar-module-into
https://stackoverflow.com/questions/64570443/q-how-to-fix-the-missing-dependancies-in-pyzbar
https://www.cnblogs.com/GengMingYan/p/15418569.html
https://blog.csdn.net/cyz141001/article/details/121714978
https://blog.csdn.net/AlanGuoo/article/details/83782958

![image](https://github.com/hiroi-sora/Umi-OCR_v2/assets/56373419/64c4e5a2-ac60-4162-bc03-6c402356c312)

似乎该问题不是个例，主要是由于系统缺失一些动态库所引起的。请尝试下载安装VC库，看看能否解决问题：
https://download.microsoft.com/download/F/3/5/F3500770-8A08-488E-94B6-17A1E1DD526F/vcredist_x64.exe

**Comment by GFDGIT** [comment]
@@hiroi-sora 
安装vc++2013 x64，可以正常运行了，感谢！
